// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Title = require("./Title.bs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(Title.make, {
          name: "Hello World!"
        }), "app");

/*  Not a pure module */
