// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

function make(label) {
  return /* record */[
          /* id */Date.now().toString(),
          /* label */label,
          /* status : Pending */0
        ];
}

var Task = /* module */[/* make */make];

var Action = /* module */[];

var initial_state_001 = /* tasks : :: */[
  make("Learn Reason"),
  /* [] */0
];

var initial_state = /* record */[
  /* input */undefined,
  initial_state_001
];

function reducer(state, action) {
  var new_state;
  if (typeof action === "number") {
    var match = state[/* input */0];
    new_state = match !== undefined ? /* record */[
        /* input */undefined,
        /* tasks : :: */[
          make(match),
          state[/* tasks */1]
        ]
      ] : state;
  } else if (action.tag) {
    var id = action[0];
    var new_tasks = List.map((function (task) {
            var match = id === task[/* id */0];
            if (match) {
              return /* record */[
                      /* id */task[/* id */0],
                      /* label */task[/* label */1],
                      /* status : Done */1
                    ];
            } else {
              return task;
            }
          }), state[/* tasks */1]);
    new_state = /* record */[
      /* input */state[/* input */0],
      /* tasks */new_tasks
    ];
  } else {
    var text = action[0];
    new_state = text === "" ? /* record */[
        /* input */undefined,
        /* tasks */state[/* tasks */1]
      ] : /* record */[
        /* input */text,
        /* tasks */state[/* tasks */1]
      ];
  }
  console.log(new_state);
  return new_state;
}

var State = /* module */[
  /* initial_state */initial_state,
  /* reducer */reducer
];

var Model = /* module */[
  /* Task */Task,
  /* Action */Action,
  /* State */State
];

function Index$Components$Task(Props) {
  var task = Props.task;
  var onDone = Props.onDone;
  var match = task[/* status */2];
  return React.createElement("li", {
              className: match ? "done" : "pending"
            }, React.createElement("button", {
                  title: "done",
                  onClick: (function (param) {
                      return Curry._1(onDone, task[/* id */0]);
                    })
                }), React.createElement("span", undefined, task[/* label */1]));
}

var Task$1 = /* module */[/* make */Index$Components$Task];

function Index$Components$ToDo(Props) {
  var match = React.useReducer(reducer, initial_state);
  var dispatch = match[1];
  var state = match[0];
  var match$1 = state[/* input */0];
  return React.createElement("div", undefined, React.createElement("form", {
                  onSubmit: (function (e) {
                      e.preventDefault();
                      return Curry._1(dispatch, /* Add_task */0);
                    })
                }, React.createElement("input", {
                      placeholder: "What do you need to do?",
                      value: match$1 !== undefined ? match$1 : "",
                      onChange: (function (e) {
                          var text = e.target.value;
                          return Curry._1(dispatch, /* Write */Block.__(0, [text]));
                        })
                    }), React.createElement("button", {
                      title: "add",
                      type: "submit"
                    })), React.createElement("ul", undefined, $$Array.of_list(List.map((function (task) {
                            return React.createElement(Index$Components$Task, {
                                        task: task,
                                        onDone: (function (param) {
                                            return /* () */0;
                                          }),
                                        key: task[/* id */0]
                                      });
                          }), state[/* tasks */1]))));
}

var ToDo = /* module */[/* make */Index$Components$ToDo];

var Components = /* module */[
  /* Task */Task$1,
  /* ToDo */ToDo
];

ReactDOMRe.renderToElementWithId(React.createElement(Index$Components$ToDo, { }), "app");

exports.Model = Model;
exports.Components = Components;
/* initial_state Not a pure module */
