// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Title(Props) {
  var name = Props.name;
  return React.createElement("h1", undefined, name);
}

var make = Title;

exports.make = make;
/* react Not a pure module */
